name: Build and Publish Docker Image to Prod and Deploy to Prod

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Publish Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/wipay-frontend:latest
          push: true
          platforms: linux/amd64

  deploy:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    name: Deploy to VPS
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Instanciate app container
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          host: ${{ secrets.SSH_HOST }}
          script: |
            bash -c "
              mkdir -p wipay
              cd wipay

              curl -H 'Authorization: token ${{ github.token }}' -o docker-compose.yml https://raw.githubusercontent.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ github.ref }}/docker-compose.yml

              docker compose pull
              docker compose down
              docker compose up -d
            "
